# -- VS Build Tools environment (required for cargo build) ----------------
$devCmd = "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
if (Test-Path $devCmd) {
    $envVars = cmd /c "`"$devCmd`" 2>nul && set" | Where-Object { $_ -match '=' }
    foreach ($var in $envVars) {
        $parts = $var -split '=', 2
        if ($parts.Count -eq 2) {
            [System.Environment]::SetEnvironmentVariable($parts[0], $parts[1], 'Process')
        }
    }
}

# -- LINUP Ollama coding helper --------------------------------------------

$prompts["F-090"] = "$mecContext

$rustDb

CONTEXT: File src-tauri/src/commands/mec.rs. DB E:\\\\linup-io\\\\linup.db. LINUP platform MEC command layer - tracks revenue share events for the LINUP control plane. Share rate: 1.5% of gross.

TASK: Output TWO blocks. 1) sql: CREATE TABLE mec_revenue_events(id TEXT PRIMARY KEY, project_id TEXT NOT NULL, app_id TEXT NOT NULL, gross_amount_pence INTEGER NOT NULL, mec_share_pence INTEGER NOT NULL, currency TEXT NOT NULL DEFAULT 'gbp', stripe_payment_intent_id TEXT, status TEXT NOT NULL DEFAULT 'pending', created_at TEXT NOT NULL); CREATE TABLE mec_entitlement_log(id TEXT PRIMARY KEY, project_id TEXT NOT NULL, feature_key TEXT NOT NULL, result TEXT NOT NULL, plan TEXT NOT NULL, checked_at TEXT NOT NULL). 2) rust: open_db() + report_revenue(project_id:String,app_id:String,gross_amount_pence:i64,currency:String,stripe_payment_intent_id:Option<String>)->Result<String,String> calculates 1.5% share INSERT mec_revenue_events return id, check_entitlement(project_id:String,feature_key:String,plan:String)->Result<bool,String> logs to mec_entitlement_log, get_mec_summary(project_id:String)->Result<MecSummary,String> MecSummary{total_gross_pence:i64,total_share_pence:i64,share_rate:f64,event_count:i64}(Serialize+Deserialize). Output ONLY two blocks. No prose."

function linup-code {
    param(
        [Parameter(Mandatory=$true)][string]$Feature,
        [string]$Task = "",
        [switch]$Interactive
    )

    try { $null = ollama list 2>&1 }
    catch {
        Write-Host "X Ollama not running. Start with: ollama serve" -ForegroundColor Red
        return
    }

    $prompts = @{}

    $prompts["F-003"] = "I'm building LINUP.IO - a Tauri v2 (Rust) + React/TypeScript desktop app.`n`nCONTEXT:`n- File: src-tauri/src/commands/stage.rs`n- tauri-plugin-sql v2 (SQLite), keyring v3`n- DB: sqlite:linup.db`n- Tables exist: projects(id,name,description,stack_preset,folder_path,budget_cap,created_at,updated_at), stage_runs(id,project_id,stage_index,status,started_at,locked_at,cost_usd)`n- Status values: locked|ready|running|awaiting_approval|gate_failed|budget_exceeded|stopped|complete`n- Commands go in src-tauri/src/commands/stage.rs`n- Register in lib.rs via tauri::generate_handler![]`n`nTASK: Write complete Rust for three Tauri commands:`n1. get_stage_model(project_id: String) -> Result<StageModel, String>`n   StageModel: { project_id: String, stages: Vec<StageRun> }`n   StageRun: { stage_index: i64, status: String, started_at: Option<String>, locked_at: Option<String>, cost_usd: f64 }`n   Create 11 stage_run rows if they don't exist yet`n2. set_stage_approved(project_id: String, stage_index: i64) -> Result<(), String>`n   Sets this stage to complete, next stage to ready. Error if not in awaiting_approval.`n3. set_stage_status(project_id: String, stage_index: i64, status: String) -> Result<(), String>`n   Validates status is one of the allowed values, updates stage_runs.`n`nWrite ONLY Rust code. Include full use statements and struct definitions."

    $prompts["F-060"] = "I'm building LINUP.IO - a Tauri v2 (Rust) + React/TypeScript desktop app.`n`nCONTEXT:`n- File: src-tauri/src/commands/secrets.rs`n- keyring v3 (NOT v2). API: Entry::new(service,user), set_password(), get_password(), delete_credential()`n- service: linup-io. Keys NEVER returned raw to TypeScript - masked only (last 4 chars)`n`nTASK: Write complete Rust for four Tauri commands:`n1. set_secret(provider: String, key: String) -> Result<(), String>`n2. get_secret_masked(provider: String) -> Result<String, String> - returns ........XXXX or Not set`n3. delete_secret(provider: String) -> Result<(), String> - use delete_credential() NOT delete_password()`n4. test_secret(provider: String) -> Result<bool, String>`n   For anthropic: GET https://api.anthropic.com/v1/models with x-api-key + anthropic-version: 2023-06-01`n   Returns Ok(true) on 200, Err with HTTP status on failure. Uses reqwest async.`n`nWrite ONLY Rust code. Include full use statements."

    $prompts["F-070"] = "I'm building LINUP.IO - a Tauri v2 (Rust) + React/TypeScript desktop app.`n`nCONTEXT:`n- File: src-tauri/src/commands/artifacts.rs`n- sha2=0.10, uuid v1, hex=0.4, tauri-plugin-sql v2`n- Artifacts at: [project_folder]/.linup/artifacts/[run_id]/[filename]`n- Append-only: never update or delete once written`n- New migration: src-tauri/migrations/003_artifacts.sql`n`nTASK: Write:`n1. SQL migration (003_artifacts.sql):`n   CREATE TABLE artifacts(id TEXT PRIMARY KEY, project_id TEXT NOT NULL, stage_index INTEGER NOT NULL, run_id TEXT NOT NULL, artifact_type TEXT NOT NULL, filename TEXT NOT NULL, content_hash TEXT NOT NULL, created_at TEXT NOT NULL, sync_status TEXT NOT NULL DEFAULT local)`n2. Rust Tauri commands:`n   write_artifact(project_id,stage_index,run_id,artifact_type,filename,content:Vec<u8>) -> Result<String,String>`n     Write to disk, SHA-256 hash via sha2, insert to SQLite, return UUID v4 artifact id`n   get_artifacts(project_id:String, stage_index:i64) -> Result<Vec<ArtifactMeta>,String>`n   read_artifact(artifact_id:String) -> Result<Vec<u8>,String>`n   verify_artifact(artifact_id:String) -> Result<bool,String> - recompute hash, compare to stored`n`nWrite ONLY Rust code and SQL. Include full use statements and struct definitions."

    $prompts["F-001"] = "I'm building LINUP.IO - a Tauri v2 + React/TypeScript (Vite) desktop app.`n`nCONTEXT:`n- Frontend root: src/ (NOT src/app/)`n- Tauri invoke: import { invoke } from '@tauri-apps/api/core'`n- CSS tokens in src/index.css: --color-surface-default, --color-accent-primary, --color-text-primary, --color-text-secondary, --color-border-default`n- SQLite command: get_projects() -> Project[]`n- Project type: { id:string, name:string, lastStage:string, lastStageState:string, budgetUsed:number, budgetCap:number, lastSynced:string }`n`nTASK: Write src/screens/ProjectsScreen.tsx with three states:`n1. Empty: centred card, headline Build a production-grade app one stage at a time, Create your first app button`n2. Has projects: 2-column grid, each card shows name/stage badge/budget bar/last synced. New app + button top-right.`n3. Offline: has-projects with full-width Offline banner and New app + disabled`n`nAlso write src/types/project.ts with Project type and StageState union type.`nUse CSS custom properties. No Tailwind. No React Router yet.`nWrite ONLY TypeScript/React code."

    $prompts["F-031"] = "I'm building LINUP.IO - a Tauri v2 + React/TypeScript (Vite) desktop app.`n`nCONTEXT:`n- File: src/components/StageStatusHeader.tsx`n- CSS tokens: --color-accent-primary(#1D4ED8), --color-budget-exceeded(#7C3AED), --color-status-success(#16A34A), --color-status-critical(#DC2626)`n- Plain React + inline styles or CSS vars only. No external libraries.`n`nTASK: Write StageStatusHeader with props:`ninterface StageStatusHeaderProps { stageName:string; stageIndex:number; stageTotal:number; state:'running'|'awaiting_approval'|'gate_failed'|'budget_exceeded'|'stopped'|'complete'; gatesPassed?:number; gatesFailed?:number; budgetSpent?:number; budgetCap?:number; onApprove?:()=>void; onRequestChanges?:()=>void; onStop?:()=>void; onChoosePath?:()=>void; onRaiseCap?:()=>void; onReduceScope?:()=>void; onViewEvidence?:()=>void; onRerun?:()=>void; }`n`nSix states: running(blue+pulsing dot+Stop), awaiting_approval(blue+gate summary+Approve+Request changes), gate_failed(red+View failed checks+Retry repair), budget_exceeded(purple #7C3AED+Cap exceeded+Raise cap+Reduce scope+Stop), stopped(purple+Choose a path full-width), complete(green+View evidence+Re-run)`n`nBottom of file: export StageStatusHeaderAllStates showing all 6 stacked for visual testing.`nWrite ONLY TypeScript/React code."

    $prompts["F-032"] = "I'm building LINUP.IO - a Tauri v2 + React/TypeScript (Vite) desktop app.`n`nCONTEXT:`n- File: src/components/EvidencePackViewer.tsx`n- color-diff-added: #DCFCE7, color-diff-removed: #FEE2E2`n- Summary mode always shown. Detail mode toggles. Approval buttons only when stageState===awaiting_approval`n`nTASK: Write EvidencePackViewer with:`ninterface DiffLine { lineNum?:number; type:'added'|'removed'|'context'; content:string; }`ninterface Artifact { name:string; status:'synced'|'not_synced'; }`ninterface GateResult { name:string; passed:boolean; description:string; }`ninterface EvidencePackViewerProps { stageNumber:number; stageName:string; whatChanged:string; why:string; risk:'low'|'medium'|'high'; gatesPassed:number; gatesFailed:number; snapshotName:string; diff?:DiffLine[]; artifacts?:Artifact[]; gateResults?:GateResult[]; stageState:'awaiting_approval'|'complete'|'gate_failed'|'running'; onApprove?:()=>void; onRequestChanges?:()=>void; onRollBack?:()=>void; defaultExpanded?:boolean; }`n`nSummary: Eye icon header + Show details toggle, what/why labels, risk badge(green/amber/red), gate count, rollback note, approval buttons.`nDetail: adds diff viewer(monospace+line numbers+coloured bg), artifact list(warning for not_synced), gate report(pass/fail icons).`nWrite ONLY TypeScript/React code."

    $prompts["F-033"] = "I'm building LINUP.IO - a Tauri v2 + React/TypeScript (Vite) desktop app.`n`nCONTEXT:`n- File: src/components/BudgetBar.tsx`n- States from ratio (NOT a prop): safe<80%(#16A34A), warning>=80%(#D97706), critical>=95%(#DC2626), exceeded(#7C3AED)`n- Exceeded: full purple bar, label shows Cap exceeded`n`nTASK: Write BudgetBar + BudgetBreakdownDrawer in same file.`ninterface StageSpend { stageName:string; spent:number; }`ninterface BudgetBarProps { spent:number; cap:number; width?:string; showViewSpend?:boolean; stageBreakdown?:StageSpend[]; }`n`nBar: 10px tall, track #E4E4E0. Below-left: GBP X.XX/X.XX monospace. Below-right: View spend link.`nDrawer: 320px wide, slides in from right, backdrop closes it, stage rows with mini bar + amount.`nWrite ONLY TypeScript/React code."

    $prompts["F-040"] = "I'm building LINUP.IO - a Tauri v2 (Rust) + React/TypeScript desktop app.`n`nCONTEXT:`n- File: src-tauri/src/commands/budget.rs`n- F-003 already owns stage_runs table. Do NOT recreate it.`n- New migration: 002_budget_columns.sql`n  ALTER TABLE stage_runs ADD COLUMN IF NOT EXISTS cost_tokens_in INTEGER NOT NULL DEFAULT 0`n  ALTER TABLE stage_runs ADD COLUMN IF NOT EXISTS cost_tokens_out INTEGER NOT NULL DEFAULT 0`n- Register as migration version 2 in lib.rs alongside version 1`n- budget_cap stored in projects.budget_cap`n- When exceeded: halt immediately, emit Tauri event budget:exceeded`n`nTASK: Write:`n1. Migration file content for 002_budget_columns.sql`n2. Rust Tauri commands:`n   check_budget(project_id:String) -> Result<BudgetStatus,String>`n     BudgetStatus: { spent:f64, cap:f64, state:String } state=Safe|Warning|Critical|Exceeded`n   raise_cap(project_id:String, new_cap:f64) -> Result<(),String>`n     Validate new_cap > current spent`n3. Pattern for emitting budget:exceeded event from Rust via AppHandle`n`nWrite ONLY Rust code and SQL."

    $prompts["F-050"] = "I'm building LINUP.IO - a Tauri v2 + React/TypeScript (Vite) desktop app.`n`nCONTEXT:`n- Files: src-tauri/src/commands/system.rs, src/stores/connectivity.ts, src/components/OfflineBanner.tsx`n- Use Tauri command for network check NOT navigator.onLine (unreliable in WebView)`n- When offline: show banner, disable run/deploy buttons, read-only mode`n`nTASK: Write:`n1. Rust command in system.rs:`n   get_connectivity_status() -> Result<ConnectivityStatus,String>`n   ConnectivityStatus: { online:bool, last_checked_at:String }`n   Implementation: HEAD request to https://api.anthropic.com with 3s timeout`n2. src/stores/connectivity.ts:`n   React context polling get_connectivity_status every 30s`n   Exposes { isOnline, lastChecked }`n3. src/components/OfflineBanner.tsx:`n   Props: state:'offline'|'reconnecting'|'reconnected'`n   offline: grey neutral banner. reconnecting: spinner. reconnected: green auto-dismiss 3s.`n`nWrite ONLY the code. No explanations."

    $prompts["F-071"] = "I'm building LINUP.IO - a Tauri v2 + React/TypeScript (Vite) desktop app.`n`nCONTEXT:`n- Files: src/types/diff.ts and src/components/DiffViewer.tsx`n- Font: JetBrains Mono. Colors: added bg #DCFCE7, removed bg #FEE2E2, context transparent`n- Must embed inside EvidencePackViewer and Stage Workspace`n`nTASK: Write:`n1. src/types/diff.ts:`n   interface DiffLine { lineNum?:number; type:'added'|'removed'|'context'; content:string; }`n   interface DiffHunk { header:string; lines:DiffLine[]; }`n   interface DiffFile { path:string; hunks:DiffHunk[]; }`n2. src/components/DiffViewer.tsx:`n   Props: { files:DiffFile[]; defaultFile?:string }`n   Left panel: file list with status icons (+ added, ~ modified, - removed)`n   Right panel: diff for selected file with line numbers and coloured backgrounds`n3. DiffViewerDemo export at bottom with hardcoded sample data`n`nWrite ONLY TypeScript/React code."

    $prompts["F-013"] = "I'm building LINUP.IO - a Tauri v2 (Rust) + React/TypeScript desktop app.`n`nCONTEXT:`n- File: src-tauri/src/commands/pipeline/stage4_product_spec.rs`n- Anthropic API key from keyring v3 (service:linup-io, user:anthropic)`n- POST https://api.anthropic.com/v1/messages, headers: x-api-key + anthropic-version:2023-06-01`n- Model: claude-sonnet-4-20250514`n- Stage index: 3 (0-based)`n- Emit stage:progress and stage:complete Tauri events`n`nTASK: Write Rust command run_stage_product_spec(app:AppHandle, project_id:String) -> Result<StageResult,String>`nStageResult: { stage_index:i64, status:String, artifact_ids:Vec<String>, gates_passed:i64, gates_failed:i64 }`nSteps: get key from keyring, load idea_intake + clarify_session artifacts, call Anthropic with system prompt You are a product specification writer produce spec with overview user stories acceptance criteria technical constraints out of scope, write response as artifact type product_spec filename product_spec.md, gate check for user stories + acceptance criteria + technical constraints (missing=fail), update stage to awaiting_approval, emit stage:complete, return StageResult.`nWrite ONLY Rust code with full use statements."

    $prompts["F-014"] = "I'm building LINUP.IO - a Tauri v2 (Rust) + React/TypeScript desktop app.`n`nCONTEXT:`n- File: src-tauri/src/commands/pipeline/stage5_architecture.rs`n- Same Anthropic API pattern as F-013. Model: claude-sonnet-4-20250514`n- Input: approved product_spec artifact. Stage index: 4. Artifact type: architecture`n`nTASK: Write Rust command run_stage_architecture(app:AppHandle, project_id:String) -> Result<StageResult,String>`nSteps: get key, load product_spec, system prompt You are a software architect produce architecture doc with data model API surfaces auth boundaries threat model top 3 risks deployment plan, write as artifact architecture.md, gates check for data model + auth + deployment, update to awaiting_approval, return StageResult.`nWrite ONLY Rust code."

    $prompts["F-015"] = "I'm building LINUP.IO - a Tauri v2 (Rust) + React/TypeScript desktop app.`n`nCONTEXT:`n- File: src-tauri/src/commands/pipeline/stage6_scaffold.rs`n- Input: approved architecture artifact. Stage index: 5.`n- Creates files for the USER's app, not LINUP itself. Default stack: Next.js + Supabase.`n- SAFE shell-out only: std::process::Command with Vec<String> args. NO string interpolation of user input.`n- Project folder from projects.folder_path in SQLite`n`nTASK: Write Rust commands:`n1. scaffold_project(app:AppHandle, project_id:String) -> Result<ScaffoldResult,String>`n   ScaffoldResult: { files_created:Vec<String>, commands_run:Vec<String>, artifact_id:String }`n   Create in project folder: package.json(Next.js+supabase-js), src/app/page.tsx(minimal), src/lib/supabase.ts(createClient with env vars), .env.example(NEXT_PUBLIC_SUPABASE_URL+ANON_KEY), supabase/migrations/.gitkeep, .gitignore`n   Write scaffold_summary.md artifact. Update stage to awaiting_approval.`n2. get_scaffold_status(project_id:String) -> Result<String,String>`n3. open_project_folder(project_id:String) -> Result<(),String> - std::process::Command::new(explorer).arg(path).spawn()`nWrite ONLY Rust code."

    $prompts["F-016"] = "I'm building LINUP.IO - a Tauri v2 (Rust) + React/TypeScript desktop app.`n`nCONTEXT:`n- File: src-tauri/src/commands/pipeline/stage7_implementation.rs`n- Stage index: 6. Diff-first. 5-file batch limit. Model: claude-haiku-4-5-20251001`n- Regression after each batch: cargo clippy + npx tsc --noEmit`n- SQLite table needed: implementation_batches(id,project_id,batch_index INTEGER,files_touched TEXT,status,artifact_id,gate_results TEXT,created_at)`n`nTASK: Write Rust commands (include CREATE TABLE SQL as comment at top):`n1. run_implementation_batch(app:AppHandle, project_id:String, feature_description:String) -> Result<BatchResult,String>`n   BatchResult: { batch_index:i64, files_changed:Vec<String>, diff_artifact_id:String, gates_passed:bool }`n   Load architecture+scaffold context, call haiku Output ONLY unified diff for max 5 files, parse filenames (error if >5), write diff artifact, run gates, store batch, update stage to awaiting_approval`n2. get_implementation_batches(project_id:String) -> Result<Vec<BatchSummary>,String>`nWrite ONLY Rust code."

    $prompts["F-017"] = "I'm building LINUP.IO - a Tauri v2 (Rust) + React/TypeScript desktop app.`n`nCONTEXT:`n- File: src-tauri/src/commands/pipeline/stage8_hardening.rs`n- Stage index: 7. SAFE shell-out only: std::process::Command with Vec<String> args.`n- Allowlist ONLY: cargo clippy, cargo test, npx eslint, npm audit. Reject others with Err(Command not permitted)`n- Model: claude-sonnet-4-20250514 for security analysis`n`nTASK: Write Rust command run_stage_hardening(app:AppHandle, project_id:String) -> Result<StageResult,String>`nGates: cargo clippy(HARD:errors>0=fail), npm audit(HARD:critical>0=fail), npx eslint src/(soft), cargo test(soft)`nFor each: capture stdout+stderr, write as artifact type gate_report`nCall Anthropic with all gate outputs for security summary, write as artifact type security_analysis`nHARD fail->gate_failed, all pass->awaiting_approval. Return StageResult.`nWrite ONLY Rust code."

    $prompts["F-018"] = "I'm building LINUP.IO - a Tauri v2 (Rust) + React/TypeScript desktop app.`n`nCONTEXT:`n- File: src-tauri/src/commands/pipeline/stage9_tests.rs`n- Stage index: 8. Read test command from package.json scripts.test at runtime. NEVER hardcode.`n- If no test script: Err(No test script in package.json. Add one before running this stage.)`n- SQLite table: test_runs(id,project_id,started_at,finished_at,exit_code INTEGER,passed INTEGER,failed INTEGER,artifact_id)`n`nTASK: Write Rust commands (include CREATE TABLE SQL as comment):`n1. run_tests(app:AppHandle, project_id:String) -> Result<TestSummary,String>`n   TestSummary: { exit_code:i32, passed:i64, failed:i64, artifact_id:String }`n   Load project folder, parse package.json scripts.test, run via Command with project folder as cwd, parse X passed/X failed patterns, write output as artifact, insert test_run, exit 0->awaiting_approval else gate_failed`n2. get_test_runs(project_id:String) -> Result<Vec<TestRunSummary>,String>`n3. read_test_log(artifact_id:String) -> Result<String,String>`nWrite ONLY Rust code."

    $prompts["F-019"] = "I'm building LINUP.IO - a Tauri v2 (Rust) + React/TypeScript desktop app.`n`nCONTEXT:`n- File: src-tauri/src/commands/pipeline/stage10_build.rs`n- Stage index: 9. Build command: pnpm tauri build -- --debug (debug) or pnpm tauri build (release)`n- Runs in LINUP project folder E:\linup-io. NO signing here (F-080/F-081 handle that).`n- SQLite table: builds(id,project_id,mode TEXT,platform TEXT,started_at,finished_at,status,artifact_id)`n`nTASK: Write Rust commands (include CREATE TABLE SQL as comment):`n1. build_desktop(app:AppHandle, project_id:String, mode:String) -> Result<BuildResult,String>`n   BuildResult: { build_id:String, platform:String, mode:String, artifact_id:String, output_path:String }`n   Run correct command, capture output as artifact type build_log, find .exe/.msi in target/debug or release/bundle, insert builds record, success->awaiting_approval, fail->gate_failed`n2. get_builds(project_id:String) -> Result<Vec<BuildSummary>,String>`n3. open_build_output(project_id:String, build_id:String) -> Result<(),String> - open folder in Explorer`nWrite ONLY Rust code."

    $prompts["F-020"] = "I'm building LINUP.IO - a Tauri v2 (Rust) + React/TypeScript desktop app.`n`nCONTEXT:`n- File: src-tauri/src/commands/pipeline/stage11_deployment.rs`n- Stage index: 10. Deploy via Vercel CLI: vercel (staging), vercel --prod (production)`n- Read .vercel/project.json from user project. NEVER hardcode project ID.`n- Production requires confirmed:true or return Err immediately.`n- SQLite table: deployments(id,project_id,target TEXT,env TEXT,status,started_at,finished_at,url TEXT,artifact_id)`n`nTASK: Write Rust commands (include CREATE TABLE SQL as comment):`n1. deploy(app:AppHandle, project_id:String, target:String, confirmed:bool) -> Result<DeployResult,String>`n   DeployResult: { deploy_id:String, url:String, artifact_id:String }`n   production+!confirmed->Err, check .vercel/project.json exists, run vercel command, extract https:// URL from output, write logs as artifact type deploy_log, insert record, success->awaiting_approval`n2. get_deploys(project_id:String) -> Result<Vec<DeploySummary>,String>`n3. rollback_deploy(project_id:String, target:String, to_version:String) -> Result<(),String> - return Err(Rollback not yet implemented - use Vercel dashboard)`nWrite ONLY Rust code."

    $prompts["F-021"] = "I'm building LINUP.IO - a Tauri v2 (Rust) + React/TypeScript desktop app.`n`nCONTEXT:`n- File: src-tauri/src/commands/pipeline/stage12_export.rs`n- Stage index: 11. Export to: [project_folder]/.linup/exports/[unix_timestamp]/`n- Portability test: copy to %TEMP%\linup-portability-test\[project_id]\, run pnpm install + pnpm run build`n- Exclude from copy: node_modules, .git, target, .env`n- SQLite table: exports(id,project_id,export_path,created_at,validation_status,validation_time_ms INTEGER)`n`nTASK: Write Rust commands (include CREATE TABLE SQL as comment):`n1. create_export(app:AppHandle, project_id:String) -> Result<ExportResult,String>`n   ExportResult: { export_id:String, export_path:String, files_included:Vec<String> }`n   Create timestamped dir, recursively copy files (skip excluded), copy stage artifacts, write instructions.md with pnpm install/dev/deploy steps + LINUP attribution, insert exports record, update stage to awaiting_approval`n2. validate_export(app:AppHandle, project_id:String, export_id:String) -> Result<ValidationResult,String>`n   ValidationResult: { passed:bool, elapsed_ms:u64, error:Option<String> }`n   Copy to TEMP, run pnpm install then pnpm run build, record elapsed ms, update exports record, passed=both exit 0`n3. open_export_folder(project_id:String, export_id:String) -> Result<(),String>`nWrite ONLY Rust code."

    $prompts["F-022"] = "I'm building LINUP.IO - a Tauri v2 (Rust) + React/TypeScript desktop app.`n`nCONTEXT:`n- File: src-tauri/src/commands/pipeline/stage13_release_notes.rs`n- Stage index: 12 - FINAL stage. Model: claude-sonnet-4-20250514.`n- Audit entries are immutable - append only, never update.`n- SQLite table: audit_trail(id,project_id,stage_index INTEGER,approved_by TEXT,approved_at TEXT,artifact_ids TEXT,gate_summary TEXT,snapshot_name TEXT)`n- approved_by: whoami::username() - add whoami=1 to Cargo.toml`n`nTASK: Write Rust commands (include CREATE TABLE SQL as comment):`n1. generate_release_notes(app:AppHandle, project_id:String) -> Result<ReleaseNotesResult,String>`n   ReleaseNotesResult: { artifact_id:String, content:String }`n   Load all approved stage artifacts 0-12, call Anthropic produce release notes markdown with Summary/What Changed/Security and Quality/Deployment Notes sections, write as artifact RELEASE_NOTES.md, update stage to complete, emit stage:complete for whole pipeline`n2. get_audit_trail(project_id:String) -> Result<Vec<AuditEntry>,String>`n3. export_audit_trail(project_id:String) -> Result<String,String> - write JSON to .linup/exports/audit_trail.json`n4. record_stage_approval(project_id:String, stage_index:i64, artifact_ids:Vec<String>, gate_summary:String) -> Result<(),String>`n   Create immutable audit entry with whoami::username()`nWrite ONLY Rust code."

    $prompts["F-041"] = "I'm building LINUP.IO - a Tauri v2 (Rust) + React/TypeScript desktop app.`n`nCONTEXT:`n- File: src-tauri/src/commands/stop_condition.rs`n- Three triggers: 1) >3 consecutive gate failures 2) budget Critical + failure rate >50% last 5 attempts 3) >2 distinct gate types failing same stage run`n- SQLite table: stop_events(id,project_id,stage_index INTEGER,reason TEXT,triggered_at TEXT,resolved_at TEXT,resolution TEXT)`n- Emit stage:stopped event with { stage_index, reason }`n`nTASK: Write Rust commands (include CREATE TABLE SQL as comment):`n1. check_stop_conditions(project_id:String, stage_index:i64) -> Result<Option<StopReason>,String>`n   StopReason: { reason:String, triggered_at:String }. Check all three. Return None or Some.`n2. record_stop_event(app:AppHandle, project_id:String, stage_index:i64, reason:String) -> Result<String,String>`n   Insert record, update stage to stopped, emit event, return stop_event_id`n3. resolve_stop_event(project_id:String, stop_event_id:String, resolution:String) -> Result<(),String>`n   resolution: raise_cap|reduce_scope|switch_to_manual|roll_back|pause`n   raise_cap/reduce_scope->ready, switch_to_manual/pause->stopped, roll_back->triggers rollback`n4. export_patch(project_id:String, stage_index:i64) -> Result<String,String>`n   Write latest diff to .linup/manual_patch/[timestamp].diff + instructions.md, open in Explorer`n5. rollback_to_snapshot(project_id:String, stage_index:i64) -> Result<(),String>`n   Find last complete stage, restore artifacts, set current stage to ready`nWrite ONLY Rust code."

    $prompts["F-080"] = "I'm building LINUP.IO - Tauri v2 desktop app. These files run on macOS GitHub Actions runners ONLY - not on Windows locally.`n`nCONTEXT:`n- Files: .github/workflows/release-macos.yml and scripts/notarise-macos.sh`n- Build: cargo tauri build --release (NOT pnpm tauri build)`n- CI secrets: APPLE_CERTIFICATE(base64 p12), APPLE_CERTIFICATE_PASSWORD, APPLE_ID, APPLE_ID_PASSWORD, APPLE_TEAM_ID`n- Bundle id: io.linup.app`n`nTASK: Write:`n1. release-macos.yml: trigger on push to release/* or workflow_dispatch with version input, runner macos-latest, steps: checkout, setup-node@v4 node 24, pnpm/action-setup@v4 pnpm 9, pnpm install, dtolnay/rust-toolchain stable, import p12 cert to keychain from APPLE_CERTIFICATE secret, cargo tauri build --release, run notarise-macos.sh with dmg path, upload .dmg artifact`n2. notarise-macos.sh (bash): args $1=DMG_PATH, xcrun notarytool submit capture UUID, poll every 30s xcrun notarytool info until Accepted or 10min timeout, on Accepted xcrun stapler staple, on fail exit 1 with message`nWrite ONLY YAML and bash."

    $prompts["F-081"] = "I'm building LINUP.IO - Tauri v2 desktop app.`n`nCONTEXT:`n- Files: .github/workflows/release-windows.yml and scripts/sign-windows.ps1`n- Build: cargo tauri build --release`n- CI secrets: WINDOWS_CERTIFICATE(base64 pfx), WINDOWS_CERTIFICATE_PASSWORD`n- Set CARGO_HTTP_CHECK_REVOKE=false in CI env`n- Bundle id: io.linup.app`n`nTASK: Write:`n1. release-windows.yml: trigger on push to release/* or workflow_dispatch, runner windows-latest, steps: checkout, setup-node@v4 node 24, pnpm/action-setup@v4, pnpm install, dtolnay/rust-toolchain, swatinem/rust-cache, set CARGO_HTTP_CHECK_REVOKE=false, cargo tauri build --release, run sign-windows.ps1, TODO VirusTotal stub, upload .msi artifact`n2. sign-windows.ps1: import cert from base64 env var to temp store, signtool.exe sign with RFC3161 timestamp http://timestamp.digicert.com, signtool.exe verify /pa, output PASS or FAIL, clean up temp cert`nWrite ONLY YAML and PowerShell."

    $prompts["F-082"] = "I'm building LINUP.IO - Tauri v2 desktop app.`n`nCONTEXT:`n- Files: src-tauri/src/commands/updater.rs and src/screens/UpdatesScreen.tsx`n- Update endpoint: https://github.com/YOUR_USERNAME/linup/releases/latest/download/latest.json`n- Three channels: canary, beta, stable`n- SQLite table: update_history(id,version TEXT,channel TEXT,applied_at TEXT,status TEXT)`n`nTASK: Write:`n1. Rust commands in updater.rs (include CREATE TABLE SQL as comment):`n   check_for_update() -> Result<Option<UpdateInfo>,String> - use tauri_plugin_updater`n   UpdateInfo: { version:String, notes:String, channel:String }`n   get_current_version() -> Result<String,String> - return tauri app version`n   get_update_channel() -> Result<String,String> - read from update_history or default stable`n   set_update_channel(channel:String) -> Result<(),String> - validate canary|beta|stable, insert record`n   get_update_history() -> Result<Vec<UpdateRecord>,String>`n2. src/screens/UpdatesScreen.tsx:`n   Shows: current version, channel selector dropdown, Check now button, last checked time, update history list (last 5)`n   Uses invoke from @tauri-apps/api/core`nWrite ONLY Rust and TypeScript code."

    # -- Check feature exists ---------------------------------------------
    $featureKey = $Feature.ToUpper()
    if (-not $prompts.ContainsKey($featureKey)) {
        Write-Host "X No prompt for: $Feature" -ForegroundColor Red
        Write-Host "  Available: $($prompts.Keys -join ', ')" -ForegroundColor Yellow
        return
    }

    $prompt = $prompts[$featureKey]
    if ($Task -ne "") { $prompt = $prompt + "`n`nADDITIONAL TASK: $Task" }

    Write-Host ""
    Write-Host "????????????????????????????????????????" -ForegroundColor DarkGray
    Write-Host "  LINUP Coder > $featureKey  [qwen2.5-coder:14b]" -ForegroundColor Cyan
    Write-Host "????????????????????????????????????????" -ForegroundColor DarkGray

    if ($Interactive) {
        $prompt | ollama run qwen2.5-coder:14b
    } else {
        $prompt | ollama run qwen2.5-coder:14b
        Write-Host ""
        Write-Host "????????????????????????????????????????" -ForegroundColor DarkGray
        Write-Host "  Next: copy code into files, then:" -ForegroundColor Green
        Write-Host "  cargo build --manifest-path src-tauri\Cargo.toml" -ForegroundColor White
        Write-Host "  npx tsc --noEmit" -ForegroundColor White
        Write-Host "  git add . && git commit -m 'feat: [$featureKey]' && git push" -ForegroundColor White
        Write-Host "????????????????????????????????????????" -ForegroundColor DarkGray
    }
}

Set-Alias lc linup-code
Write-Host "linup-code ready. Usage: lc F-060  |  lc F-003 -Interactive  |  lc F-013 -Task 'only the SQL'" -ForegroundColor Green
