pub const SPEC_TEMPLATE_SECTIONS: &[(&str, u8, &str)] = &[
    ("1. Document Control & Governance", 1, "Mandatory"),
    ("2. Project Vision & Objectives", 1, "Mandatory"),
    ("3. Stakeholders & Project Roles", 1, "Mandatory"),
    ("4. User Research & Personas", 2, "Mandatory"),
    ("5. Platform & Environment Definition", 4, "Mandatory"),
    ("6. System Architecture Overview", 4, "Mandatory"),
    ("7. Design System & UX Specifications", 3, "Mandatory"),
    ("8. User Stories, Screen Flows & Functional Requirements", 1, "Mandatory"),
    ("9. Authentication & Authorisation", 4, "Mandatory"),
    ("10. Data Architecture", 5, "Mandatory"),
    ("11. API & Integration Specifications", 4, "Mandatory"),
    ("12. Third-Party & External Integrations", 4, "Conditional"),
    ("13. Notifications & Communications", 3, "Conditional"),
    ("14. Offline, Sync & Background Processing", 4, "Conditional"),
    ("15. Performance & Reliability", 4, "Mandatory"),
    ("16. Security Requirements", 6, "Mandatory"),
    ("17. Accessibility Requirements", 7, "Mandatory"),
    ("18. Internationalisation & Localisation", 3, "Conditional"),
    ("19. Analytics, Instrumentation & Observability", 5, "Mandatory"),
    ("20. Error Handling & Logging", 4, "Mandatory"),
    ("21. Testing Strategy & Quality Gates", 7, "Mandatory"),
    ("22. Deployment, CI/CD & Release Management", 8, "Mandatory"),
    ("23. Legal, Compliance & Privacy", 9, "Mandatory"),
    ("24. Content & UX Writing Standards", 3, "Conditional"),
    ("25. Support & Documentation Plan", 8, "Conditional"),
    ("26. Cost & Infrastructure Budget", 8, "Conditional"),
    ("27. Risk Register", 8, "Mandatory"),
    ("28. Acceptance Criteria & Sign-Off", 0, "Mandatory"),
];